### ISSUE TITLE
Licensing for NodeMCU

### ISSUE THREAD

**Issue by Starofall** [spapadim/XPT2046#2]
Hello spapadim,

I have created a port using parts of your lib for the NodeMCU framework and would like to merge it with the dev branch - see merge request [1]. As NodeMCU is MIT licensed and your lib is GPL I wanted to ask if you might change the license or at least allow the merge.

[1] - https://github.com/nodemcu/nodemcu-firmware/pull/1242

**Comment by marcelstoer** [comment]
@spapadim I'm with the NodeMCU project and would really appreciate if you could provide some feedback here. We'd love to have support for XPT2046 touch screens.

**Comment by spapadim** [comment]
Hi --

Absolutely no objection. I am not familiar with license compatibility
issues, but would rather not change the license to MIT, if there are
alternatives.

Cheers,
Spiros

**Comment by marcelstoer** [comment]
Thanks a lot Spiros!

I'm no OSS license expert but if I'm not mistaken the biggest difference between GPL and more permissive licenses like MIT is that GPL-components require that all components based upon it to be FLOSS as well. Hence, if NodeMCU used your GPL code everyone using NodeMCU would have to open-source their own proprietary code because it's indirectly dependent on your code.

I have no idea how legally binding your "Absolutely no objection." statement above is but we certainly appreciate that you don't object 😃. Of course you could always dual-license your code to support both models.

**Comment by urielka** [comment]
👍  would love to see this too :)

IMNAL but had my fair share of working with OSS licenses with one of the big companies out there...
If you are building closed-source code then GPL is a big no-no.

Dual licensing is a good option, I use MIT on all my things since (IMO) it is more liberal.

**Comment by spapadim** [comment]
Yep, did some reading on Wikipedia after replying.
1. Approving merge: No idea either what would be legally binding (IM _so_
   NAL :) ), and a signed "Contributor License Agreement" somehow seems
   overkill for a small piece of code like this (although I'd also be happy to
   do that on my end).
2. License choice: Dual licensing MIT+GPL sounds pointless. Also no
   objection to switching to a permissive license. From the little I've read,
   I'd prefer Apache (mostly on a matter of principle, as I don't really see
   patents involved in this).  Anyone know for sure if that would be
   MIT-compatible?  If yes, great. If not, MIT is ok too for this tiny project.
3. Switching: Finally, what does it take to switch license?  Just push a
   commit changing the LICENSE file (and header comments, which I see I
   totally forgot here :)?

**Comment by marcelstoer** [comment]
> I'd prefer Apache ...  Anyone know for sure if that would be MIT-compatible?

According to https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses it is.

> Finally, what does it take to switch license? Just push a commit changing the LICENSE file...

Yes (I believe) but to simplify things I'd do it like this:
- make a release e.g. version 1.0
- switch the license
- make another release e.g. v1.1

Then you could argue that pre-1.1 versions are GPL and all versions above are <whatever>.

**Comment by spapadim** [comment]
Thx -- saw that figure in many places. However, similar to your argument
that merging GPL will require the end result to follow GPL (i.e., NodeMCU
and anyone using it will have to open-source everything they've done), my
understanding of that figure is that merging Apache _might_ require NodeMCU
to switch to Apache (i.e., NodeMCU and anyone contributing to it may have
to grant patent rights to all NodeMCU users) -- although, again, my
understanding is very vague (to put it mildly).

In any case, even though all this has been.. educational (at least for me),
I feel I've been educated more than enough for now :) , so I'll just switch
this to MIT.

Will follow your suggestion wrt making a release etc. Should be done in the
next couple of days (traveling currently).
