### ISSUE TITLE
touch rotation

### ISSUE THREAD

**Issue by andreaguiar** [spapadim/XPT2046#3]
Hi, I have the exact same screen and esp and I used your tutorial to connect it all. I'm trying to rotate the touch but I can't seem to understand how to do so. Can you help me? Thanks

**Comment by spapadim** [comment]
Sorry -- question is too vague. In general, after calibrating (with rotation ROT0 as noted in source), just setRotation() to the desired orientation (on both the touch driver, as well as whatever display library you're using).

**Comment by andreaguiar** [comment]
Thanks for answering. 
So in the XPTPaint for exemple, for the TFT I put tft.setRotation(3); but for the touch what should I put?

**Comment by spapadim** [comment]
It's been a while since I touched this code, but I _think_ I followed the
same convention as ucglib. In any case, guessing it should be either 3
(ROT270) or 1 (ROT90), whichever turns out to match your display library.

**Comment by andreaguiar** [comment]
I should have mentioned that I'm new to all of this... My problem was the syntax... but I just checked your new code and saw touch.setRotation(touch.ROT270); tried it and it worked! Great!
Btw I tried your new code and it says "Error compiling for board NodeMCU 1.0 (ESP-12E Module)", is that normal?
